apiVersion: v1
kind: PersistentVolume #1. podajemy rodzaj
metadata:
  name: pv01 #2. nazwa
spec:
  accessModes: #3. accessmode, tryb dostepu
    - ReadWriteOnce # ReadOnlyMany ReadWriteMany 
  capacity: #4. Podajemy pojemnosc dysku
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain # 5. polityka jesli chodzi o zwalnianie 
  storageClassName: "host-path" #6. nazwa storage'u 
  hostPath:
    path: /data/pv01 #7. fizyczny storage path
---
apiVersion: v1
kind: PersistentVolumeClaim #8. Zadanie dostepu/ volumenu
metadata:
  name: pvc01
spec:
  accessModes: #9. Accessmode request, storageclassname musza sie zgadzac i byc takie same
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "host-path"
  volumeName: pv01
---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  terminationGracePeriodSeconds: 0
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc01 #10. wartosc z gory, z metadata: name: pvc01
  containers:
    - name: toolbox
      image: pnowy/toolbox:1.0.0
      workingDir: "/app"
      command: ["sh", "-c"]
      args:
        - mkdir -p /app && echo "Work done $HOSTNAME $(date +%Y-%m-%d_%H-%M-%S)" >> /app/data.txt && sleep infinity
      volumeMounts: #11. trzeba podpiac do konkretnego kontenera
        - mountPath: /app
          name: data